version: '3.3'

networks:
  integration:
    driver: "bridge"

services:
  postgresql:
    container_name: postgresql_vw
    build:
      context: .
      dockerfile: ./Dockerfile.postgresql
    networks:
      - "integration"
    environment:
      - "POSTGRES_MULTIPLE_DATABASES=kafka"
      - "POSTGRES_USER=carnet"
      - "POSTGRES_PASSWORD=carnet"
    ports:
      - "54321:5432"
    restart: always
  zookeeper:
    container_name: zookeeper
    networks:
      - "integration"
    image: 'bitnami/zookeeper:3.8.1'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: kafka
    networks:
      - "integration"
    image: 'bitnami/kafka:3.4.0'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - 'KAFKA_OPTS: -javaagent:/usr/app/jmx_prometheus_javaagent.jar=7071:/usr/app/prom-jmx-agent-config.yml'
    depends_on:
      - zookeeper
